// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/appointment/all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有预约信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "appointments"
                ],
                "summary": "获取所有预约信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Appointment"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/appointment/submit": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "提交预约",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "appointments"
                ],
                "summary": "提交预约",
                "parameters": [
                    {
                        "description": "预约数据",
                        "name": "appointmentData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Appointment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/models.Appointment"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/appointment/{appointmentID}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据预约ID获取预约",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "appointments"
                ],
                "summary": "根据预约ID获取预约",
                "parameters": [
                    {
                        "type": "string",
                        "description": "预约ID",
                        "name": "appointmentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/models.Appointment"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除预约",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "appointments"
                ],
                "summary": "删除预约",
                "parameters": [
                    {
                        "type": "string",
                        "description": "预约ID",
                        "name": "appointmentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/attachment/upload": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "上传附件",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attachments"
                ],
                "summary": "上传附件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "附件文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "病例ID",
                        "name": "caseID",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/change-password": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "修改密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "修改密码请求",
                        "name": "changePassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/current-user": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取当前登录用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "获取当前登录用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取所有病例",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/diagnosed": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有已诊断的病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取已诊断的病例",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/diagnosed/{username}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据专家用户名获取所有已诊断的病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取专家已诊断的病例",
                "parameters": [
                    {
                        "type": "string",
                        "description": "专家用户名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/case/excel": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "导出病例Excel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "导出病例Excel",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/pending/{username}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据专家用户名获取所有待处理的病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取专家待处理的病例",
                "parameters": [
                    {
                        "type": "string",
                        "description": "专家用户名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/case/pendingdiagnosis": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有待诊断的病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取待诊断的病例",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/returned": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有已退回的病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取已退回的病例",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/returned/{username}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据专家用户名获取所有已退回的病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取专家已退回的病例",
                "parameters": [
                    {
                        "type": "string",
                        "description": "专家用户名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/case/submit": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "提交病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "提交病例",
                "parameters": [
                    {
                        "description": "病例数据",
                        "name": "caseData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Case"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/models.Case"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/toDiagnosed/{caseID}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新状态：到已诊断",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "更新状态：到已诊断",
                "parameters": [
                    {
                        "type": "string",
                        "description": "病例ID",
                        "name": "caseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/toPendingdiagnosis/{caseID}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新状态：到待诊断",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "更新状态：到待诊断",
                "parameters": [
                    {
                        "type": "string",
                        "description": "病例ID",
                        "name": "caseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/toReturned/{caseID}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新状态：到被退回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "更新状态：到被退回",
                "parameters": [
                    {
                        "type": "string",
                        "description": "病例ID",
                        "name": "caseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/toWithdraw/{caseID}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新状态：到撤回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "更新状态：到撤回",
                "parameters": [
                    {
                        "type": "string",
                        "description": "病例ID",
                        "name": "caseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/unsubmitted": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有未提交的病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取未提交的病例",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/withdraw": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有已撤回的病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取已撤回的病例",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/withdraw/{username}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据专家用户名获取所有已撤回的病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取专家已撤回的病例",
                "parameters": [
                    {
                        "type": "string",
                        "description": "专家用户名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/case/{caseID}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据病例ID获取病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "根据病例ID获取病例",
                "parameters": [
                    {
                        "type": "string",
                        "description": "病例ID",
                        "name": "caseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/models.Case"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "删除病例",
                "parameters": [
                    {
                        "type": "string",
                        "description": "病例ID",
                        "name": "caseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/case/{caseID}/print": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "增加打印次数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "增加打印次数",
                "parameters": [
                    {
                        "type": "string",
                        "description": "病例ID",
                        "name": "caseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/expert": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有专家",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experts"
                ],
                "summary": "获取专家列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Expert"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/expert/all/{username}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据专家用户名获取所有病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "获取专家所有病例",
                "parameters": [
                    {
                        "type": "string",
                        "description": "专家用户名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Case"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/expert/excel/{username}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据专家用户名导出所有病例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "导出专家所有病例",
                "parameters": [
                    {
                        "type": "string",
                        "description": "专家用户名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/expert/{username}/appointments": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据专家用户名获取所有预约",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "appointments"
                ],
                "summary": "获取专家所有预约",
                "parameters": [
                    {
                        "type": "string",
                        "description": "专家用户名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Appointment"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/slice/upload": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "上传切片",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slices"
                ],
                "summary": "上传切片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "切片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "病例ID",
                        "name": "caseID",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "错误响应",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "newPassword": {
                    "description": "新密码\nRequired: true\nExample: 654321",
                    "type": "string",
                    "example": "654321"
                },
                "oldPassword": {
                    "description": "旧密码\nRequired: true\nExample: 123456",
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "handlers.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "role",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码\nRequired: true\nExample: 123456",
                    "type": "string",
                    "example": "123456"
                },
                "role": {
                    "description": "角色\nRequired: true\nExample: admin",
                    "type": "string",
                    "example": "admin"
                },
                "username": {
                    "description": "用户名\nRequired: true\nExample: admin",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "middleware.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "错误信息"
                }
            }
        },
        "models.Appointment": {
            "type": "object",
            "properties": {
                "appointmentAt": {
                    "description": "预约时间",
                    "type": "string"
                },
                "appointmentID": {
                    "description": "预约编号",
                    "type": "string"
                },
                "appointmentStatus": {
                    "description": "预约状态",
                    "type": "string"
                },
                "clinicalDoctor": {
                    "description": "临床医生",
                    "type": "string"
                },
                "expert": {
                    "description": "专家",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Expert"
                        }
                    ]
                },
                "expertID": {
                    "description": "关联专家",
                    "type": "integer"
                },
                "hospital": {
                    "description": "送检医院",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "patientAge": {
                    "description": "年龄",
                    "type": "string"
                },
                "patientGender": {
                    "description": "性别",
                    "type": "string"
                },
                "patientName": {
                    "description": "姓名",
                    "type": "string"
                },
                "patientPhone": {
                    "description": "联系电话",
                    "type": "string"
                },
                "remarks": {
                    "description": "备注",
                    "type": "string"
                },
                "submitAt": {
                    "description": "提交时间",
                    "type": "string"
                },
                "surgeryLocation": {
                    "description": "手术部位",
                    "type": "string"
                }
            }
        },
        "models.Attachment": {
            "type": "object",
            "properties": {
                "caseID": {
                    "description": "案例ID",
                    "type": "string"
                },
                "fileID": {
                    "description": "附件ID",
                    "type": "string"
                },
                "fileName": {
                    "description": "附件名称",
                    "type": "string"
                },
                "filePath": {
                    "description": "附件路径",
                    "type": "string"
                },
                "fileSize": {
                    "description": "附件大小",
                    "type": "integer"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                }
            }
        },
        "models.Case": {
            "type": "object",
            "properties": {
                "attachments": {
                    "description": "关联附件",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Attachment"
                    }
                },
                "barCode": {
                    "description": "条形码",
                    "type": "string"
                },
                "bedNo": {
                    "description": "床号",
                    "type": "string"
                },
                "biopsySite": {
                    "description": "取材部位",
                    "type": "string"
                },
                "caseID": {
                    "description": "病例号",
                    "type": "string"
                },
                "caseStatus": {
                    "description": "病例状态",
                    "type": "string"
                },
                "checkupNo": {
                    "description": "体检编号",
                    "type": "string"
                },
                "clinicalData": {
                    "description": "临床资料",
                    "type": "string"
                },
                "clinicalDiagnosis": {
                    "description": "临床诊断",
                    "type": "string"
                },
                "clinicalPhone": {
                    "description": "临床电话",
                    "type": "string"
                },
                "consultationID": {
                    "description": "诊断相关",
                    "type": "string"
                },
                "diagnoseAt": {
                    "description": "诊断时间",
                    "type": "string"
                },
                "diagnosisContent": {
                    "description": "诊断内容、诊断结果",
                    "type": "string"
                },
                "diagnosisRemarks": {
                    "description": "诊断备注",
                    "type": "string"
                },
                "expert": {
                    "description": "专家",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Expert"
                        }
                    ]
                },
                "expertDiagnosisOpinion": {
                    "description": "专家诊断意见",
                    "type": "string"
                },
                "expertID": {
                    "description": "关联专家",
                    "type": "integer"
                },
                "grossFinding": {
                    "description": "肉眼所见",
                    "type": "string"
                },
                "hospital": {
                    "description": "送检医院",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "immunohistochemistry": {
                    "description": "免疫组化",
                    "type": "string"
                },
                "inpatientNo": {
                    "description": "门诊、住院号",
                    "type": "string"
                },
                "maritalStatus": {
                    "description": "婚姻状况",
                    "type": "string"
                },
                "mirrorDescription": {
                    "description": "镜下描述",
                    "type": "string"
                },
                "pathologicalDiagnosis": {
                    "description": "病理诊断",
                    "type": "string"
                },
                "pathologyType": {
                    "description": "病理类型",
                    "type": "string"
                },
                "patientAddress": {
                    "description": "病人地址",
                    "type": "string"
                },
                "patientAge": {
                    "description": "病人年龄",
                    "type": "integer"
                },
                "patientGender": {
                    "description": "病人性别",
                    "type": "string"
                },
                "patientName": {
                    "description": "病人姓名",
                    "type": "string"
                },
                "patientPhone": {
                    "description": "病人电话",
                    "type": "string"
                },
                "patientType": {
                    "description": "病人类型",
                    "type": "string"
                },
                "printCount": {
                    "description": "打印",
                    "type": "integer"
                },
                "receiveDate": {
                    "description": "接收日期",
                    "type": "string"
                },
                "remarks": {
                    "description": "备注",
                    "type": "string"
                },
                "sampleDate": {
                    "description": "采样日期",
                    "type": "string"
                },
                "slices": {
                    "description": "关联切片",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Slice"
                    }
                },
                "submitAt": {
                    "description": "时间",
                    "type": "string"
                },
                "tissueCount": {
                    "description": "组织数量",
                    "type": "integer"
                }
            }
        },
        "models.Expert": {
            "type": "object",
            "properties": {
                "cases": {
                    "description": "关联字段",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Case"
                    }
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "hospital": {
                    "description": "医院",
                    "type": "string"
                },
                "id": {
                    "description": "专家ID",
                    "type": "integer"
                },
                "nickName": {
                    "description": "专家名称",
                    "type": "string"
                },
                "password": {
                    "description": "专家密码",
                    "type": "string"
                },
                "phone": {
                    "description": "电话",
                    "type": "string"
                },
                "role": {
                    "description": "专家角色",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                },
                "username": {
                    "description": "专家用户名",
                    "type": "string"
                }
            }
        },
        "models.Slice": {
            "type": "object",
            "properties": {
                "caseID": {
                    "description": "病例ID",
                    "type": "string"
                },
                "fileName": {
                    "description": "文件名",
                    "type": "string"
                },
                "filePath": {
                    "description": "文件路径",
                    "type": "string"
                },
                "fileSize": {
                    "description": "文件大小",
                    "type": "integer"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "sliceID": {
                    "description": "切片号",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Enter the token with the ` + "`" + `Bearer: ` + "`" + ` prefix, e.g. \"Bearer abcde12345\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8085",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Online Diagnosis System API",
	Description:      "This is the API documentation for the Online Diagnosis System.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
